name: wgpack
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - anyio
  - appnope
  - argon2-cffi
  - async_generator
  - attrs
  - babel
  - backcall
  - backports
  - backports.functools_lru_cache
  - bcrypt
  - beautifulsoup4
  - blas
  - bleach
  - brotli
  - brotlipy
  - bs4
  - c-ares
  - ca-certificates
  - cached-property
  - cached_property
  - certifi
  - cffi
  - cftime
  - charset-normalizer
  - cryptography
  - curl
  - cycler
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - fonttools
  - freetype
  - geographiclib
  - geopy
  - h5py
  - hdf4
  - hdf5
  - icu
  - idna
  - importlib-metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - isodate
  - jedi
  - jinja2
  - jpeg
  - json5
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - kiwisolver
  - krb5
  - lcms2
  - libcurl
  - libcxx
  - libedit
  - libev
  - libffi
  - libgfortran
  - libiconv
  - libnetcdf
  - libnghttp2
  - libpng
  - libsodium
  - libssh2
  - libtiff
  - libwebp-base
  - libxml2
  - libxslt
  - lxml
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munkres
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - netcdf4
  - notebook
  - numpy
  - numpy-base
  - olefile
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - paramiko
  - parso
  - pexpect
  - pickleshare
  - pillow
  - pip
  - platformdirs
  - proj
  - prometheus_client
  - prompt-toolkit
  - ptyprocess
  - pycparser
  - pygments
  - pynacl
  - pyopenssl
  - pyparsing
  - pyproj
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytz
  - pyzmq
  - readline
  - requests
  - requests-file
  - requests-toolbelt
  - requests-unixsocket
  - seawater
  - send2trash
  - setuptools
  - six
  - sniffio
  - soupsieve
  - sqlite
  - terminado
  - testpath
  - tk
  - tornado
  - traitlets
  - tzdata
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - xz
  - zeep
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - matlabengineforpython
